plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android' version '1.9.10'
}

android {
    namespace "com.example.camerabarcode"
    compileSdk 35

    defaultConfig {
        minSdk 24
        targetSdk 35
        consumerProguardFiles 'consumer-rules.pro'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

repositories {
    google()
    mavenCentral()
}

dependencies {
    implementation project(':capacitor-android')

    // AndroidX AppCompat
    implementation 'androidx.appcompat:appcompat:1.7.0'
    
    def cx = "1.4.1" // hoặc 1.4.0 cũng được, miễn đồng bộ giữa các camera-*
    implementation "androidx.camera:camera-core:$cx"
    implementation "androidx.camera:camera-camera2:$cx"
    implementation "androidx.camera:camera-lifecycle:$cx"
    implementation "androidx.camera:camera-view:$cx"
    implementation "androidx.camera:camera-video:$cx"
    implementation "androidx.camera:camera-effects:$cx"

    // ML Kit Barcode
    implementation 'com.google.mlkit:barcode-scanning:17.2.0'

    // Core KTX
    implementation 'androidx.core:core-ktx:1.13.1'
}