pluginManagement {
  repositories {
    google()
    mavenCentral()
    gradlePluginPortal()
  }
  plugins {
    // Khai báo version plugin ở đây để module dưới có thể dùng
    id("com.android.library") version "8.6.0"
    id("org.jetbrains.kotlin.android") version "2.0.20"
  }
}

dependencyResolutionManagement {
  repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
  repositories {
    google()
    mavenCentral()
  }
}

rootProject.name = "capacitor-camera-barcode"
